### ISSUE TITLE
Issue #1 still occurs (space bar not functioning after completing WQ)

### ISSUE THREAD

**Issue by Gaviin1242** [p3lim-wow/QuestAutomation#3]
As noted in the comment in issue #1, this issue still seems to be occurring.  When I completed "We'll Make an Aspirant Out of You" today on both my druid and shaman, the space bar doesn't revert to its proper functioning.  It instead activates the '4' button.

I'm using v90100.6-Release.

**Comment by Cluuey** [comment]
I came to report the same thing but I have a bit more detail.
I'm using _Version: 90105.7-Release_.

With _We'll Make an Aspirant Out of You_ space bar doesn't work after you complete the quest, however if you run away before filling the progress bar it does work!
For _A More Civilized Way_ it works fine,
I've not done the other ones recently, while my account is active I'm not playing much.

With _Taming the Wilderling_ it felt like it wasn't as quick when I did it with a Kyrian character but then on my Night Fae it was, I've not actually timed it so it's very subjective. Initially I thought they'd broken it with a hotfix but when I changed characters it only took triggering it three times so I just thought I was going mad.

**Comment by Odysseas68** [comment]
I also use the  `Version: 90105.7-Release` and i have the same problem with `We'll Make an Aspirant Out of You` .

**Comment by p3lim** [comment]
> space bar doesn't work after you complete the quest, however if you run away before filling the progress bar it does work!

Thanks for this one @Cluuey, made it really easy to spot the error.

**Comment by p3lim** [comment]
Please try out this alpha version, the WQ is up right now:  
https://github.com/p3lim-wow/QuestAutomation/suites/5390300131/artifacts/169692308

Tried it myself and it seems to work fine.
